# This file is a part of MRNIU/printf
# (https://github.com/MRNIU/printf).
#
# workflow.yml for MRNIU/printf.

name: build

on:
  - push
  - pull_request
  - release

env:
  CMAKE_BUILD_TYPE: Release

jobs:
  build:
    name: Build and publish documentation
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install --fix-missing -y gcc g++

      - name: Build printf
        run: |
          cmake --build build --target printf
          cmake --build build --target printf_test
