# This file is a part of MRNIU/printf_bare_metal
# (https://github.com/MRNIU/printf_bare_metal).
#
# workflow.yml for MRNIU/printf_bare_metal.

name: build

on:
  - push
  - pull_request
  - release

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install --fix-missing -y gcc g++ libgtest-dev

      - name: Build printf_bare_metal
        run: |
          cmake --preset debug
          cmake --build debug --target printf_bare_metal
          cmake --build debug --target printf_bare_metal_test
