# This file is a part of MRNIU/printf_bare_metal
# (https://github.com/MRNIU/printf_bare_metal).
#
# workflow.yml for MRNIU/printf_bare_metal.

name: build

on:
  - push
  - pull_request
  - release

env:
  CMAKE_BUILD_TYPE: Release

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install --fix-missing -y gcc g++

      - name: Build printf
        run: |
          cmake --preset build
          cmake --build build --target printf
          cmake --build build --target printf_test
